name: Deploy
on:
  push:
    branches:
      - main

jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: client
          useLockFile: false

      - name: 🔬 Lint
        run: npm run lint

  typecheck:
    name: TypeScript
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: client
          useLockFile: false

      - name: 🔎 Type check
        run: npm run typecheck --if-present

  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          dir: server
          name: 'config/default.json'
          json: ${{ secrets.DEFAULT_JSON_SECRET }}

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: client
          useLockFile: false

      - name: Start Backend
        working-directory: server
        run: npm run start &

      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v4
        with:
          working-directory: client
          start: npm start
          wait-on: 'http://localhost:3000'
        env:
          REACT_APP_TMDB_KEY: ${{ secrets.REACT_APP_TMDB_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
